"""Convert the previously reviewed independent transcription into an editable AI project."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from ai_score.contracts import default_format, validate_score
from ai_score.providers import write_json
from ai_score.render import render


def make_example():
    source = json.loads((ROOT/'independent_score/transcription.json').read_text(encoding='utf-8'))
    meta = dict(title='Ado | Bass TAB', instrument='bass', numbered=True, first_bar=1,
                last_bar=143, meter=[4, 4], bpm=145, key_fifths=0, strings=4,
                crop=[0, 0, 1, 1], observations=[])
    bars = []
    marks = {'i': 'slide-in', 'o': 'slide-down', 'u': 'slide-up', 't': 'tie-start',
             'c': 'tie-stop', 'h': 'hammer-start', 'S': 'slap', 'P': 'pop', 'v': 'vibrato'}
    for number, original in source['bars'].items():
        events, onset = [], 0
        for e in original:
            notes = []
            if e['string']:
                notes = [dict(string='GDAE'.index(e['string'])+1, fret=e['fret'], step='',
                              alter=0, octave=0, drum='', marks=' '.join(marks[m] for m in e['marks'] if m in marks))]
            events.append(dict(onset=onset, duration=e['duration'], voice=1, staff=1, notes=notes, marks=''))
            onset += e['duration']
        bars.append(dict(number=int(number), meter=[4, 4], pickup=False, events=events,
                         confidence=1., timestamp=0., issues=[]))
    score = dict(version=1, source=source['source'], meta=meta, bars=bars, observations=[],
                 review=[], provenance='Previously reviewed independent visual transcription; not generated by the new AI app.')
    assert not validate_score(score), validate_score(score)
    score['layout'] = default_format(meta['title'], 4)
    score['layout']['merge_rests'] = [[116, 117]]
    target = ROOT/'independent_score/ai_example'
    target.mkdir(exist_ok=True)
    write_json(target/'Ado.aiscore.json', score)
    render(score, score['layout'], target/'Ado_clean_merged_rest.pdf')
    print(target/'Ado_clean_merged_rest.pdf')
    return score


if __name__ == '__main__':
    make_example()
