const {_electron: electron} = require('playwright');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');

(async () => {
  const root = path.resolve(__dirname,'..');
  const executablePath = process.env.SCORE_TEST_EXECUTABLE;
  const app = await electron.launch({executablePath,
    args:executablePath ? [`--user-data-dir=${path.join(root,'diagnostics','packaged-desktop-profile')}`] : ['-r',path.join(__dirname,'test-profile.cjs'),root],
    cwd:root,env:{...process.env,ELECTRON_DISABLE_SECURITY_WARNINGS:'true'}});
  const page = await app.firstWindow();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.waitForFunction(() => document.querySelector('#status')?.textContent.includes('Choose a video'));
  const screenshot = async name => { await page.screenshot({path:path.join(root,'diagnostics',name+'.png')}); };
  try {
    assert.equal(await page.locator('#gap').inputValue(),'0');
    assert.equal(await page.locator('#left-margin').inputValue(),'3');
    assert.equal(await page.locator('#right-margin').inputValue(),'3');
    await screenshot('electron-empty');
    await page.locator('#source').fill(path.join(root,'samples','kgNjaXTh0rU.mp4'));
    await page.locator('#load-video').click();
    await page.waitForFunction(() => !document.querySelector('#extract').disabled, null, {timeout:120000});
    await page.waitForFunction(() => document.querySelector('video').readyState >= 2 && !document.querySelector('video').seeking);
    await page.locator('video').evaluate(node => node.currentTime = 20);
    await page.waitForFunction(() => !document.querySelector('video').seeking);
    await screenshot('electron-capture');
    await page.locator('#advanced').evaluate(node => node.open = true);
    await page.locator('#end').fill('15');
    await page.locator('#extract').click();
    await page.waitForFunction(() => !document.querySelector('#review-screen').hidden, null, {timeout:60000});
    assert.ok(await page.locator('.line-item').count());
    await page.locator('#edit-line').click();
    await page.waitForFunction(() => document.querySelector('#editor-image').naturalWidth > 0);
    await screenshot('electron-crop-editor');
    await page.locator('#crop-top').fill('60');
    await page.locator('#crop-top').dispatchEvent('change');
    await page.locator('#crop-bottom').fill('99');
    await page.locator('#crop-bottom').dispatchEvent('change');
    await page.locator('#apply-edit').click();
    await page.waitForFunction(() => !document.querySelector('#editor').open);
    await page.locator('#edit-line').click();
    assert.equal(await page.locator('#crop-top').inputValue(), '60.0');
    await page.locator('#reset-line').click();
    await page.waitForFunction(() => !document.querySelector('#editor').open);
    await page.locator('#pdf-title').fill('Desktop test score');
    await page.locator('#for-print').click();
    assert.equal(await page.locator('#gap').inputValue(),'0');
    assert.equal(await page.locator('#left-margin').inputValue(),'12');
    assert.equal(await page.locator('#right-margin').inputValue(),'12');
    const downloads = [];
    await app.evaluate(({session}, folder) => {
      session.defaultSession.removeAllListeners('will-download');
      session.defaultSession.on('will-download', (_event,item) => { item.setSavePath(`${folder}/${item.getFilename()}`); });
    }, path.join(root,'diagnostics'));
    page.on('download', download => downloads.push(download));
    await page.locator('#save-project').click();
    await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Desktop test score.drumscore'));
    await page.locator('#export-pdf').click();
    await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Desktop test score.pdf'));
    await page.waitForFunction(() => !document.querySelector('#export-pdf').disabled);
    await screenshot('electron-review');
    await page.locator('#capture-tab').click();
    await page.locator('#manual').click();
    await page.waitForFunction(() => !document.querySelector('#add-line').disabled);
    const bounds = await page.locator('#video-crop').boundingBox();
    await page.mouse.move(bounds.x+bounds.width*.05, bounds.y+bounds.height*.8);
    await page.mouse.down();
    await page.mouse.move(bounds.x+bounds.width*.95, bounds.y+bounds.height*.97, {steps:8});
    await page.mouse.up();
    await page.waitForFunction(() => !document.querySelector('#add-line').disabled);
    await page.locator('#add-line').click();
    await page.waitForFunction(() => document.querySelector('#manual-count').textContent === '1');
    await page.locator('#play').click();
    await page.waitForFunction(() => !document.querySelector('video').paused);
    await page.locator('#review-tab').click();
    assert.ok(await page.locator('video').evaluate(node => node.paused));
    await page.setViewportSize({width:390,height:844});
    await screenshot('electron-mobile-review');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.setViewportSize({width:1280,height:800});
    await app.evaluate(({dialog}, filename) => { dialog.showOpenDialog = async () => ({canceled:false,filePaths:[filename]}); }, path.join(root,'diagnostics','Desktop test score.drumscore'));
    await page.locator('#open-project').click();
    await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Project opened'));
    await page.locator('#edit-line').click();
    await page.waitForFunction(() => document.querySelector('#editor-image').naturalWidth > 0);
    assert.ok((await page.locator('#editor-hint').textContent()).includes('expand'));
    await page.locator('#cancel-edit').click();
    assert.equal(await page.locator('#pdf-title').inputValue(), 'Desktop test score');
    assert.ok(fs.statSync(path.join(root,'diagnostics','Desktop test score.pdf')).size > 1000);
    assert.ok(fs.statSync(path.join(root,'diagnostics','Desktop test score.drumscore')).size > 1000);
    await page.locator('#capture-tab').click();
    await screenshot('electron-mobile-capture');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.deepEqual(errors, []);
    console.log('Passed: Electron load, automatic extraction, crop edit/reset, title-named project/PDF, manual capture/playback, mobile layout.');
  } catch (error) {
    console.error(await page.locator('#status').textContent(), await page.locator('#error-text').textContent());
    console.error('page errors:', errors);
    await screenshot('electron-failure');
    throw error;
  } finally { await app.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
